#medium_type = "ram" / "unk"     / "cart" / "ddrive"
#sequence_player = "sfx" / "fanfare" / "bgm"  / "demo"
medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 117
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_625"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_625"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 105
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_651"
			tuning = 0.333710
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 227
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_652"
			tuning = 1.334840
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 231
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_621"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Unk_602"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Unk_603"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Unk_604"
			tuning = 0.629961
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 117
		env_rate = [
			2, 1, 433, -1,
		]
		env_level = [
			32700, 32700, 0, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_616"
			tuning = 0.841847
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "F#5"
		split_lo = "A1"
		release_rate = 211
		env_rate = [
			21, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_580"
			tuning = 0.516214
		[inst.entry.hi]
			sample = "Unk_581"
			tuning = 0.365018
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "F5"
		split_lo = "D4"
		release_rate = 93
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 0, 0, 0,
		]
		[inst.entry.low]
			sample = "Unk_594"
			tuning = 2.317721
		[inst.entry.prim]
			sample = "Unk_595"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Unk_391"
			tuning = 0.500000
	[[inst.entry]]
		split_hi = "F5"
		split_lo = "A3"
		release_rate = 186
		env_rate = [
			2, 229, 1, -1,
		]
		env_level = [
			32700, 0, 0, 0,
		]
		[inst.entry.low]
			sample = "Unk_594"
			tuning = 2.317721
		[inst.entry.prim]
			sample = "Unk_595"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Unk_391"
			tuning = 0.500000

