#medium_type = "ram" / "unk"     / "cart" / "ddrive"
#sequence_player = "sfx" / "fanfare" / "bgm"  / "demo"
medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "G4"
		release_rate = 174
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 0, 0, 0,
		]
		[inst.entry.low]
			sample = "Unk_643"
			tuning = 1.781798
		[inst.entry.prim]
			sample = "Unk_644"
			tuning = 0.890899
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 236
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_378"
			tuning = 0.629961
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "D#5"
		release_rate = 239
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Unk_612"
			tuning = 2.378414
		[inst.entry.prim]
			sample = "Unk_653"
			tuning = 0.594604
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_605"
			tuning = 0.396850
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 246
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_596"
			tuning = 0.594604
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 246
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_609"
			tuning = 0.629961
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_382"
			tuning = 0.333710
		[inst.entry.hi]
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "G#6"
		split_lo = "A1"
		release_rate = 234
		env_rate = [
			2, 1, 421, -1,
		]
		env_level = [
			32700, 32700, 0, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_387"
			tuning = 0.890899
		[inst.entry.hi]
			sample = "Unk_591"
			tuning = 0.222725
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Unk_602"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Unk_603"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Unk_604"
			tuning = 0.629961
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Unk_602"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Unk_603"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Unk_604"
			tuning = 0.629961
	[[inst.entry]]
		split_hi = "F#5"
		split_lo = "A1"
		release_rate = 211
		env_rate = [
			21, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_580"
			tuning = 0.516214
		[inst.entry.hi]
			sample = "Unk_581"
			tuning = 0.365018
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "G#4"
		release_rate = 186
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Unk_627"
			tuning = 0.974482
		[inst.entry.prim]
			sample = "Unk_628"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 248
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_654"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 248
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Unk_617"
			tuning = 0.689062
		[inst.entry.hi]
[drum]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.222725
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.235969
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.250000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.264866
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.280616
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.297302
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.314980
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.333710
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.353553
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.374577
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.396850
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.420448
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.445449
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.471937
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.500000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.529732
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.561231
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.594604
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.629961
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.667420
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.707107
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.749154
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.793701
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.840897
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.890899
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 0.943875
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Unk_384"
		tuning = 1.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 71
		release_rate = 0
		sample = "Unk_592"
		tuning = 1.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 71
		release_rate = 0
		sample = "Unk_592"
		tuning = 1.059463
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.059463
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.122462
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.189207
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.259921
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.334840
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.414214
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.498307
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.587401
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.681793
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.781798
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 1.887749
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 2.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 2.118926
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 2.244924
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 2.378414
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 2.519842
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 2.669680
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 2.828428
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 2.996615
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 3.174803
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 3.363586
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 3.563596
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 3.775498
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 4.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 4.237853
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 4.489849
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 4.756829
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 5.039685
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 5.339360
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 5.656855
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 5.993229
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 6.349606
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 6.727173
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Unk_385"
		tuning = 7.127192
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]

